// tripsData.ts
export const trips = [
    {
      id: "1",
      time: "07:30",
      company: "Hà Lan",
      rating: 5,
      seatsAvailable: 12,
      totalSeats: 24,
      price: 650000,
      discount: 200000,
      extras: ["WiFi", "A/C", "+3"],
      date: "02/03/2021",
      origin: "Hà Nội",
      destination: "Nghệ An",
      vehicleType: "Sedan",
    },
    {
      id: "2",
      time: "07:30",
      company: "Hà Lan",
      rating: 5,
      seatsAvailable: 24,
      totalSeats: 24,
      price: 650000,
      discount: 200000,
      extras: ["WiFi", "A/C", "+3"],
      date: "02/03/2021",
      origin: "Hà Nội",
      destination: "Nghệ An",
      vehicleType: "SUV",
    },
    {
      id: "3",
      time: "07:30",
      company: "Hà Lan",
      rating: 5,
      seatsAvailable: 12,
      totalSeats: 24,
      price: 650000,
      discount: 200000,
      extras: ["WiFi", "A/C", "+3"],
      date: "03/03/2021",
      origin: "Hà Nội",
      destination: "Hà Tĩnh",
      vehicleType: "Hatchback",
    },
    {
      id: "4",
      time: "07:30",
      company: "Hà Lan",
      rating: 5,
      seatsAvailable: 12,
      totalSeats: 24,
      price: 650000,
      discount: 200000,
      extras: ["WiFi", "A/C", "+3"],
      date: "01/09/2024",
      origin: "Hà Nội",
      destination: "Nghệ An",
      vehicleType: "Taxi",
    },{
      id: "5",
      time: "17:30",
      company: "Hà Lan",
      rating: 5,
      seatsAvailable: 12,
      totalSeats: 24,
      price: 650000,
      discount: 200000,
      extras: ["WiFi", "A/C", "+3"],
      date: "01/09/2024",
      origin: "Hà Nội",
      destination: "Nghệ An",
      vehicleType: "Hatchback",
    },
  ];
  